name: Build and Release
'on':
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    name: Upload APK to App Tester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: '17'
      - name: Write & validate debug google-services.json
        run: |
          set -e
          mkdir -p composeApp/src/debug
          echo "$GOOGLE_SERVICES_JSON_DEBUG_B64" | base64 -d > composeApp/src/debug/google-services.json
          # (opcionális) BOM eltávolítás, ha lenne
          sed -i '1s/^\xEF\xBB\xBF//' composeApp/src/debug/google-services.json || true
          # Gyors szerkezeti ellenőrzés
          jq . composeApp/src/debug/google-services.json > /dev/null
          grep -q '"project_info"' composeApp/src/debug/google-services.json
          grep -q '"client"' composeApp/src/debug/google-services.json
          grep -q '"package_name"[[:space:]]*:[[:space:]]*"hu\.blu3berry\.sunny\.dev"' composeApp/src/debug/google-services.json
        env:
          GOOGLE_SERVICES_JSON_DEBUG_B64: ${{ secrets.GOOGLE_SERVICES_JSON_DEBUG_B64 }}

      - name: build release
        run: bash ./gradlew assembleDebug
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.1
        with:
          appId: ${{ secrets.SUNNY_ANDROID_APP_ID_DEBUG }}
          serviceCredentialsFileContent:  ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS_FILE_CONTENT }}
          groups: family-and-friends
          file: app/build/outputs/apk/debug/app-debug.apk

