name: SonarCloud Analysis
on:
  push:
    branches: [ main, kmp_with_analyze_tools ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'    # REQUIRED for setup-java@v3
          java-version: 17
          cache: 'gradle'           # optional, speeds up builds

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Write & validate debug google-services.json
        env:
          GOOGLE_SERVICES_JSON_DEBUG_B64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE_64 }}
        run: |
          set -e
          if [ -z "${GOOGLE_SERVICES_JSON_DEBUG_B64:-}" ]; then
            echo "::error:: Secret GOOGLE_SERVICES_JSON_DEBUG_B64 is empty or not set."
            exit 1
          fi
          mkdir -p composeApp/src/release
          echo "$GOOGLE_SERVICES_JSON_DEBUG_B64" | base64 -d > composeApp/src/release/google-services.json
          sed -i '1s/^\xEF\xBB\xBF//' composeApp/src/release/google-services.json || true
          jq . composeApp/src/release/google-services.json > /dev/null
          grep -q '"project_info"' composeApp/src/release/google-services.json
          grep -q '"client"' composeApp/src/release/google-services.json
          grep -q '"package_name"[[:space:]]*:[[:space:]]*"hu\.blu3berry\.sunny\.dev"' composeApp/src/release/google-services.json
#       Currently there are no tests, so no coverage to report is needed
#      - name: Generate Kover reports
#        run: ./gradlew koverXmlReport
      - name: Run SonarCloud Analysis
        run: |
          ./gradlew sonar --stacktrace --info \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}